HelpInfo,D:\Microsemi\Libero_SoC_v12.6\SynplifyPro\lib\html,fpgahelp.qhc,synerrmsg.mp,D:\Microsemi\Libero_SoC_v12.6\SynplifyPro\bin\assistant
Implementation;Synthesis||FX1184||@N: Applying syn_allowed_resources blockrams=21 on top level netlist HW4_Q3A ||HW4_Q3A.srr(185);liberoaction://cross_probe/hdl/file/'<project>\synthesis\HW4_Q3A.srr'/linenumber/185||null;null
Implementation;Synthesis||FX1143||@N: Skipping assigning INTERNAL_VREF to iobanks, because the table of mapping from pin to iobank is not initialized.||HW4_Q3A.srr(211);liberoaction://cross_probe/hdl/file/'<project>\synthesis\HW4_Q3A.srr'/linenumber/211||null;null
Implementation;Synthesis||MO231||@N: Found counter in view:work.HW4_Q3A(verilog) instance Q[23:0] ||HW4_Q3A.srr(280);liberoaction://cross_probe/hdl/file/'<project>\synthesis\HW4_Q3A.srr'/linenumber/280||hw4_q3a.v(38);liberoaction://cross_probe/hdl/file/'<project>\hdl\HW4_Q3A.v'/linenumber/38
Implementation;Synthesis||FP130||@N: Promoting Net clk_c on CLKINT  I_2 ||HW4_Q3A.srr(308);liberoaction://cross_probe/hdl/file/'<project>\synthesis\HW4_Q3A.srr'/linenumber/308||null;null
Implementation;Synthesis||FP130||@N: Promoting Net rst_n_c on CLKINT  I_3 ||HW4_Q3A.srr(309);liberoaction://cross_probe/hdl/file/'<project>\synthesis\HW4_Q3A.srr'/linenumber/309||null;null
Implementation;Synthesis||MT615||@N: Found clock clk with period 20.00ns ||HW4_Q3A.srr(358);liberoaction://cross_probe/hdl/file/'<project>\synthesis\HW4_Q3A.srr'/linenumber/358||null;null
Implementation;Place and Route;RootName:HW4_Q3A
Implementation;Place and Route||(null)||Please refer to the log file for details about 6 Info(s)||HW4_Q3A_layout_log.log;liberoaction://open_report/file/HW4_Q3A_layout_log.log||(null);(null)
